language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

jdk: oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
